### ISSUE TITLE
文件解码问题

### ISSUE THREAD

**Issue by 127161782** [Coldwave96/WebShell-AIHunter#1]
在分词前，需要将文本读取，这时不都是UTF-8，你是如何解决的，我用chardet模块，检测出编码规则，用其解码，也不好使

**Comment by Coldwave96** [comment]
大部分的正常代码都是可以解码的，加密或者混淆的脚本很大可能本身就有问题，所以解码这个事不是一个好想法，最好能另外寻找代码不可读情况的解决办法

**Comment by Coldwave96** [comment]
> 在分词前，需要将文本读取，这时不都是UTF-8，你是如何解决的，我用chardet模块，检测出编码规则，用其解码，也不好使

大部分的正常代码都是可以解码的，加密或者混淆的脚本很大可能本身就有问题，所以解码这个事不是一个好想法，最好能另外寻找代码不可读情况的解决办法
